Number_of_boids: 50

starting_positions: 
    x_range: [-450.0,50.0]
    y_range: [300.0,600.0]
starting_velocities:
    x_range: [0,10.0]
    y_range: [-20.0,20.0]

fly_towards_middle_coeff: 0.01
avoid_nearby_birds_cutoff: 100
match_speed:
    cutoff: 10000
    coeff: 0.125    

plot:
    x_axis_range: [-500,1500]
    y_axis_range: [-500,1500]
    frames: 50
    interval: 50

